name: Render_ontology

on:
  push:
    branches:
      - main

jobs:
  Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Render
        run: |
          python render_once.py --output_path rendered-for-gh-pages
          pwd
          find rendered-for-gh-pages

      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: rendered-for-gh-pages
