name: Render_ontology

on:
  push:
    branches:
      - main

jobs:
  Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: pip3 install 'rasaeco==0.0.8'

      - name: Render
        run: |
          cp -R ontology rendering

          # We need to delete .gitignore as otherwise the files will be ignored in actions-gh-pages
          find rendering -name ".gitignore" -exec rm {} \;

          pyrasaeco-render once --scenarios_dir rendering
          cp rendering/ontology.html rendering/index.html
          pwd
          find rendering

      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: rendering
